export { createClient } from './supabase';
export {
  DASHBOARD_HOME,
  getRolesRequiredForDashboardPath,
  isGuestAuthPath,
  isMiddlewareGuestSuccessRedirectPath,
  userHasDashboardPathAccess,
  type UserRole,
} from './auth-routes';
export { apiFetch, getAccessToken, ApiError } from './api-client';
export {
  fetchMe,
  registerProfile,
  recoverPassword,
  getOnboardingStatus,
  createOnboardingCompany,
  createOnboardingFirstVehicle,
  createOnboardingFirstDriver,
  getMyCompany,
  updateMyCompany,
  getExpenseCategories,
  createExpenseCategory,
  updateExpenseCategory,
  deleteExpenseCategory,
  getVehicles,
  getVehicle,
  createVehicle,
  updateVehicle,
  deleteVehicle,
  uploadVehiclePhoto,
  getDrivers,
  getDriver,
  createDriver,
  updateDriver,
  deleteDriver,
  uploadDriverPhoto,
  getCompanyStaff,
  createCompanyStaffUser,
  updateCompanyStaffUser,
  deleteCompanyStaffUser,
  resendCompanyStaffInvite,
  type CreateCompanyStaffResponse,
  type UpdateCompanyStaffPayload,
  getTrips,
  getTrip,
  createTrip,
  updateTrip,
  deleteTrip,
  getExpensesByTrip,
  uploadExpenseReceipt,
  createExpense,
  updateExpense,
  deleteExpense,
  getAdvancesByTrip,
  uploadAdvanceReceipt,
  createAdvance,
  updateAdvance,
  deleteAdvance,
  finalizeTrip,
  getSettlement,
  markSettlementPaid,
  type AuthUser,
  type OnboardingStatus,
  type CreateOnboardingCompanyPayload,
  type CreateOnboardingFirstVehiclePayload,
  type CreateOnboardingFirstDriverPayload,
  type Company,
  type UpdateCompanyPayload,
  type ExpenseCategoryItem,
  type ExpenseCategoriesResponse,
  type CreateExpenseCategoryPayload,
  type UpdateExpenseCategoryPayload,
  type Vehicle,
  type VehicleStatus,
  type CreateVehiclePayload,
  type UpdateVehiclePayload,
  type Driver,
  type DriverStatus,
  type DriverPreferredVehicle,
  type CreateDriverPayload,
  type UpdateDriverPayload,
  type CompanyStaffMember,
  type CompanyStaffResponse,
  type CreateCompanyStaffPayload,
  type Trip,
  type TripStatus,
  type TripVehicle,
  type TripDriver,
  type CreateTripPayload,
  type UpdateTripPayload,
  type Expense,
  type ExpenseCategoryRef,
  type CreateExpensePayload,
  type UpdateExpensePayload,
  type Advance,
  type AdvanceMethod,
  type CreateAdvancePayload,
  type UpdateAdvancePayload,
  type Settlement,
  type SettlementWithTrip,
} from '@/services/api';

