export {
  digitsOnly,
  formatCpf,
  formatCnpjMask,
  formatCpfCnpjDocument,
  formatPhoneBr,
  formatBrlCurrencyInput,
  numberToBrlInputDigits,
  parseBrlInputString,
  formatKmInput,
  parseKmInputString,
  isValidCnpj,
} from './br-format';
export { createClient } from './supabase';
export {
  DASHBOARD_HOME,
  getRolesRequiredForDashboardPath,
  isGuestAuthPath,
  isMiddlewareGuestSuccessRedirectPath,
  userHasDashboardPathAccess,
  type UserRole,
} from './auth-routes';
export { apiFetch, getAccessToken, ApiError } from './api-client';
export {
  fetchMe,
  registerProfile,
  recoverPassword,
  patchAuthProfile,
  uploadAuthProfilePhoto,
  getOnboardingStatus,
  createOnboardingCompany,
  createOnboardingFirstVehicle,
  createOnboardingFirstDriver,
  getMyCompany,
  updateMyCompany,
  getSubscriptionStatus,
  postSubscriptionCheckout,
  postSubscriptionPortal,
  type SubscriptionPlan,
  type SubscriptionPlanKey,
  type SubscriptionStatusResponse,
  type SubscriptionStatusValue,
  type PaginationOptions,
  type PaginatedResult,
  getExpenseCategories,
  createExpenseCategory,
  updateExpenseCategory,
  deleteExpenseCategory,
  getVehicles,
  getVehiclesPage,
  getVehicle,
  createVehicle,
  updateVehicle,
  deleteVehicle,
  uploadVehiclePhoto,
  getDrivers,
  getDriversPage,
  getDriver,
  createDriver,
  updateDriver,
  deleteDriver,
  uploadDriverPhoto,
  getCompanyStaff,
  createCompanyStaffUser,
  updateCompanyStaffUser,
  deleteCompanyStaffUser,
  resendCompanyStaffInvite,
  getDashboardSummary,
  getDashboardCharts,
  type CreateCompanyStaffResponse,
  type UpdateCompanyStaffPayload,
  getTrips,
  getTripsList,
  getTripsReport,
  reportsTripsQueryKey,
  defaultMonthlyReportRange,
  getTripsPage,
  getTrip,
  createTrip,
  updateTrip,
  deleteTrip,
  startTrip,
  setTripDeliveryReceipt,
  getExpensesByTrip,
  getExpensesByTripPage,
  uploadExpenseReceipt,
  createExpense,
  updateExpense,
  deleteExpense,
  getAdvancesByTrip,
  getAdvancesByTripPage,
  uploadAdvanceReceipt,
  createAdvance,
  updateAdvance,
  deleteAdvance,
  finalizeTrip,
  getSettlement,
  markSettlementPaid,
  isDisplacementFinalizeResult,
  type AuthUser,
  type OnboardingStatus,
  type CreateOnboardingCompanyPayload,
  type CreateOnboardingFirstVehiclePayload,
  type CreateOnboardingFirstDriverPayload,
  type Company,
  type AutonomousDriverRef,
  type CommissionCalculationMethod,
  type UpdateCompanyPayload,
  type ExpenseCategoryItem,
  type ExpenseCategoriesResponse,
  type CreateExpenseCategoryPayload,
  type UpdateExpenseCategoryPayload,
  type Vehicle,
  type VehiclePairRef,
  type VehicleType,
  VEHICLE_TYPE_LABELS,
  type VehicleStatus,
  type CreateVehiclePayload,
  type UpdateVehiclePayload,
  type Driver,
  type DriverStatus,
  type DriverPreferredVehicle,
  type CreateDriverPayload,
  type UpdateDriverPayload,
  type CompanyStaffMember,
  type CompanyStaffResponse,
  type CreateCompanyStaffPayload,
  type OwnerDashboardSummary,
  type OwnerDashboardCharts,
  type DriverDashboardSummary,
  type DashboardSummary,
  type Trip,
  type TripsListResponse,
  type TripsReportData,
  type TripStatus,
  type TripVehicle,
  type TripDriver,
  type CreateTripPayload,
  type UpdateTripPayload,
  type Expense,
  type ExpenseCategoryRef,
  type CreateExpensePayload,
  type UpdateExpensePayload,
  type Advance,
  type AdvanceMethod,
  type CreateAdvancePayload,
  type UpdateAdvancePayload,
  type Settlement,
  type SettlementWithTrip,
  type FinalizeTripResult,
} from '@/services/api';

